# Site settings
title: dmdwns2의 저장소
description: "이것저것 기록합니다."
url: "http://www.dmdwns2.github.io/home"
ogimage: "img/favicon.png"
author:
  name: "EungJun Kim"
  email: "ssreki1@naver.com"
  url: "https://github.com/dmdwns2"


# Build settings
baseurl: /home # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
