# Site settings
title: 개인 기록 저장소
description: "이것저것 기록합니다."
url: "https://dmdwns2.github.io"
ogimage: "img/favicon.png"
author:
  name: "dmdwns2"
  email: ""
  url: "https://github.com/dmdwns2"


# Build settings
baseurl: # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:categories/:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
markdown: kramdown
kramdown:
  input: GFM
  
# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

# 포스트 안보이는 문제 해결
timezone: Asia/Seoul
future: true
locale: "ko-KR"